table D_Produtos

	/// Chave inteira do produto.
	column ID_Produto
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ID_Produto

	/// Nome comercial do produto.
	column Produto
		dataType: string
		summarizeBy: none
		sourceColumn: Produto

	column Media_Unidades_Vendidas
		dataType: decimal
		formatString: #,##0.00
		summarizeBy: none
		sourceColumn: Media_Unidades_Vendidas

	column Media_Valor_Vendas
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: none
		sourceColumn: Media_Valor_Vendas

	column Mediana_Valor_Vendas
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: none
		sourceColumn: Mediana_Valor_Vendas

	column Maior_Valor_Venda
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: none
		sourceColumn: Maior_Valor_Venda

	column Menor_Valor_Venda
		dataType: decimal
		formatString: $#,##0.00
		summarizeBy: none
		sourceColumn: Menor_Valor_Venda

	partition D_Produtos = m
		mode: import
		source =
			let
			    // Resume cada produto em uma linha e calcula os indicadores solicitados no desafio.
			    AgrupadoPorProduto = Table.Group(
			        Financials_Origem,
			        {"Product"},
			        {
			            {"Media_Unidades_Vendidas", each List.Average([Units Sold]), Currency.Type},
			            {"Media_Valor_Vendas", each List.Average([Sales]), Currency.Type},
			            {"Mediana_Valor_Vendas", each List.Median([Sales]), Currency.Type},
			            {"Maior_Valor_Venda", each List.Max([Sales]), Currency.Type},
			            {"Menor_Valor_Venda", each List.Min([Sales]), Currency.Type}
			        }
			    ),
			    AdicionouIndiceProduto = Table.AddColumn(
			        AgrupadoPorProduto,
			        "ID_Produto",
			        each
			            if [Product] = "Carretera" then 0
			            else if [Product] = "Montana" then 1
			            else if [Product] = "Paseo" then 2
			            else if [Product] = "Velo" then 3
			            else if [Product] = "VTT" then 4
			            else if [Product] = "Amarilla" then 5
			            else null,
			        Int64.Type
			    ),
			    RenomeouProduto = Table.RenameColumns(AdicionouIndiceProduto, {{"Product", "Produto"}}),
			    ReordenouColunas = Table.ReorderColumns(
			        RenomeouProduto,
			        {"ID_Produto", "Produto", "Media_Unidades_Vendidas", "Media_Valor_Vendas", "Mediana_Valor_Vendas", "Maior_Valor_Venda", "Menor_Valor_Venda"}
			    )
			in
			    ReordenouColunas
